<?php

return [
    /* Key (for translation) => Prompt (in english) */
    '3d_render' => '3D Render',
    'pixel' => 'Pixel art',
    'sticker' => 'Sticker illustration',
    'isometric' => 'Isometric',
    'cyberpunk' => 'Cyberpunk art',
    'vaporwave' => 'Vaporwave art',
    'steampunk' => 'Steampunk art',
    'glitchcore' => 'Glitchcore art',
    'bauhaus' => 'Bauhaus art',
    'vector' => 'Vector art',
    'low_poly' => 'Low poly art',
    'ukiyo_e' => 'Ukiyo-e',
    'line' => 'Line art',
    'pencil' => 'Pencil drawing art',
    'ballpoint_pen' => 'Ballpoint pen drawing art',
    'watercolor' => 'Watercolor art',
    'origami' => 'Origami art',
    'cartoon' => 'Cartoon art',
    'retro' => 'Retro art',
    'anime' => 'Anime art',
    'renaissance' => 'Renaissance art',
    'clay' => 'Clay art',
    'cubism' => 'Cubism art',
    'modern' => 'Modern art',
    'pop' => 'Pop art',
    'contemporary' => 'Contemporary art',
    'impressionism' => 'Impressionism art',
    'pointillism' => 'Pointillism art',
    'minimalism' => 'Minimalism art',
];
